### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by crshnbrn66** [kewalaka/cCDROMdriveletter#1]
Great job on your Resource.  When first running it. it's not evident that you need to use a colon with the drive name.  

For consistency I suggest that you change your resource to allow for just the drive letter ....  If you use the xDisk resource from xStorage that is the convention that is used there.

        cCDROMdriveletter BDrive
        {
            DriveLetter = 'B:'
            Ensure = 'Present'
        }

        cCDROMdriveletter BDrive
        {
            DriveLetter = 'B'
            Ensure = 'Present'
        }

**Comment by kewalaka** [comment]
hi - thanks for the feedback, I've mostly used this as a learning exercise, but I've posted a fix as you suggest, both here and to the PSGallery.
