### ISSUE TITLE
Suggest sending this into PS DSC Resource Kit's xStorage repository

### ISSUE THREAD

**Issue by johlju** [kewalaka/cCDROMdriveletter#3]
Hi,

I like to suggest sending this into PS DSC Resource Kit's [xStorage](https://github.com/PowerShell/xStorage) repository. Though, I think the resource should be change to be a single instance resource. See https://msdn.microsoft.com/en-us/powershell/dsc/singleinstance.

I have a case open over at xStorage for a resource like this https://github.com/PowerShell/xStorage/issues/96. @Zuldan commented that you already created a resource for this, it feels unnecessary to invent the wheel again. 😄 

I'm happy to help in any way. I see there is no tests yet, if you like I could write tests for the resource when you PR this into xStorage. Just let me if I can be of any assistance.

**Comment by kewalaka** [comment]
@johlju sure - will take a look.  It was a learning exercise in creating a DSC resource and getting Appveyor going.  It might take me a while. I've not got heaps of time at the moment, busy trying to convince my company that Infrastructure as Code is the future, but it would be rather pleasing to get this into an official resource,  Appreciate the help re testing, I really should learn Pester!

**Comment by johlju** [comment]
There is no hurry. But if you would like, you could start by sending in a PR, then I could help you modify the resource by sending you PR's (which you must approve) towards that working branch. Happy to help in any way I can.

I know the feeling about Infrastructure as Code. This is a young technology in regards for the Windows world, so it's hard breaking old habits of golden images, click-installs and click-configuration. But one small step at a time and eventually this will be the standard. 😄 

Regarding Pester. It is not so difficult once you get the hang of it. A good source for learning is this https://leanpub.com/pesterbook

**Comment by kewalaka** [comment]
see https://github.com/PowerShell/xStorage/pull/99

**Comment by johlju** [comment]
This has been merged in xStorage repo! Thanks a bunch @kewalaka!
